# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# Spring 基础配置
spring:
  application:
    name: easy-log
  profiles:
    active: dev

  # 数据源配置（MySQL）
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # 连接池配置[1](@ref)

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新表结构[1,6](@ref)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # 格式化SQL输出[4](@ref)

  # 安全配置
  security:
    user:
      name: admin
      password: admin123
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-server.com  # JWT认证服务地址[1](@ref)

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.example.demo: DEBUG  # 自定义包日志级别[1,3](@ref)

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有监控端点[1](@ref)
  endpoint:
    health:
      show-details: always

# 自定义配置
custom:
  api:
    rate-limit: 1000/分钟  # 接口限流配置
    cache-ttl: 30m  # 缓存过期时间
  feature-flags:
    new-payment: true  # 功能开关[1](@ref)